---
title: "cs490proposal"
output: 
  pdf_document:
    template: template.tex

---

\maketitle


\section{Overview}
One of my favorite classes at Yale was CPSC 460: Automata Theory. We studied fundamental models of computation and worked on proofs and algorithms throughout the class which connected the models to one another. We discussed finite state automaton and their relationship with regular languages, pushdown automaton and their relationship with context-free grammar, \& turing machines and their relationship to recursively enumerable languages. Each of these computational models can be used to accept certain languages (or solve certain types of algorithms). To fully understand the material and proofs in the course it was helpful to visualize the computational models. My project will be a tool which aids in the analysis and visualization of these models. 



\section{Project Description}
The process of converting an automaton to a language or to a grammar is non-trivial. We proved that the conversion process is possible and discussed possible algorithms for doing so. However there becomes another issue finding the most simplified machine, language, or grammar. There is existing software (e.g. JFLAP created at Duke) which aims to solve the conversion and minimization problems regarding automata. However, this tool is a bit clunkly and not intuitive. My goal is to create a clean, easy-to-use graphical utility that will:

\begin{itemize}
\item Create a DFA, NFA, and Turing machine
\item Simulate a DFA, NFA, and Turing machine
\item Convert between NFA, DFA, and minimal DFA
\item Convert between NFA and regular expression
\item If time permits I will add in features related to PDAs and CFGs.
\end{itemize}

A major component of my project will be the development process. My plan is to create a public website which will have interactive graphics. I will spend a significant amount of time learning the web dev process geared for user interaction. I am in a computer graphics class and will hopefully get a chance to apply knowledge from that class in this project. Morever the project will reinforce key concepts about the fundamental models of computation and renew my interest in the theory of computation. 

\section{Implementation}
I will use a Python framework (either Flask or Django) for the back-end. On the front-end I will use JavaScript libraries (React and D3) to create and display the visuals. I've never fully implemented an interactive website before so the project will be a valueable learning experience. There are many free resources online to aid in the development learning process. 

\section{Deliverables}
\begin{enumerate}
\item Full project source code on GitHub
\item Publically accessible website
\item Screen captures of examples
\item Description about the process of building an interactive web app
\end{enumerate}

\section{Future Use}
I wanted to pick a project that will have value for the community in the future. I am interested in education and building software to assit with learning. My hope is that future students of CPSC 460 will use the tool I build. The main difference between my project and existing software will be the ease of use. The exiting software in this are a pain to download and are not intuitive to use; these issues prevent beginners from using the tool at all. My utility will solve these and allow students with no experience with automata to play around and analyze. 
